"""
main.py - A runnable multi-agent "crew" built with CrewAI.

THE STORY THIS CODE TELLS
-------------------------
A single language-model call is a smart generalist with no process. For any
non-trivial task it tends to do everything in one breath: research, write, and
judge its own work all at once. The result is usually shallow and self-
flattering, because the model rarely catches its own mistakes.

A *multi-agent system* splits that one job into specialists that hand work to
each other, exactly like a small newsroom:

    Orchestrator  ->  Researcher  ->  Writer  ->  Critic
                                         ^            |
                                         |____________|
                                      "send it back"

  * Orchestrator - decides the order of work and passes outputs along.
                   In CrewAI this is the Crew + Process itself, not a separate
                   agent you write by hand.
  * Researcher   - gathers and organizes the raw facts.
  * Writer       - turns those facts into a clean article.
  * Critic       - checks the draft and can demand revisions.

This file also includes a FOURTH agent, a Curriculum Designer, whose job is to
turn the crew's work into the teaching content that fills index.html. It outputs
structured JSON (not prose), which we parse and write to content.json. The HTML
page fetches that file, so the interactive lesson is generated BY the crew rather
than hand-written. See the build_curriculum_task() docstring for details.

CrewAI hides the plumbing. You describe WHO the agents are (role / goal /
backstory) and WHAT the tasks are, then wire the tasks together with
`context=[...]`. The framework handles the prompting, the ordering, and the
passing of each result into the next step. The handoff_demo.py file in this
repo does the same thing by hand so you can see what CrewAI abstracts away.

HOW TO RUN
----------
    pip install -r requirements.txt
    cp .env.example .env   # then fill in GEMINI_API_KEY (read in automatically)
    python main.py "your research topic"
"""

import json
import os
import re
import sys

# Loads variables from a .env file in this folder into the environment, so you
# don't have to `export` the API key by hand every session.
from dotenv import load_dotenv

# CrewAI's public building blocks. `LLM` is CrewAI's thin wrapper around
# litellm, which is what lets us point at Google Gemini instead of OpenAI.
from crewai import Agent, Task, Crew, Process, LLM

load_dotenv()


# Where the teaching content the crew produces gets written. index.html fetches
# this file on load.
CONTENT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "content.json")


def build_llm() -> LLM:
    """Create the shared language model that every agent will use.

    We use Google's Gemini *free tier*. CrewAI talks to it through litellm, and
    the model id `gemini/gemini-2.5-flash` is the signal that routes the call to
    Google rather than to OpenAI. The API key is read from the environment so no
    secret ever lives in the source code.
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        # Fail loudly and helpfully. A confusing auth error three layers deep in
        # litellm is the most common thing that trips up first-time learners.
        sys.exit(
            "\nERROR: GEMINI_API_KEY is not set.\n"
            "\nThis project runs for FREE on Google's Gemini free tier.\n"
            "  1. Get a key (free, no credit card): https://aistudio.google.com/apikey\n"
            "  2. Copy .env.example to .env and paste the key in:\n"
            "       cp .env.example .env\n"
            "  3. Re-run:    python main.py \"your topic\"\n"
        )
    # temperature is kept modest so the researcher stays factual; the writer and
    # critic inherit the same model. You could give each agent its own LLM with
    # different settings, which is a common real-world tuning step.
    #
    # Provider note: CrewAI 1.x reaches Gemini through its native google-genai
    # client (listed in requirements.txt). The "gemini/..." model id selects
    # that provider; the client reads GEMINI_API_KEY and uses the same free
    # tier. If you would rather use the older litellm path, run
    # `pip install litellm` and add is_litellm=True to this call.
    #
    # The model defaults to gemini-2.5-flash, which has working free-tier quota
    # as of this writing (gemini-2.0-flash currently shows "limit: 0" on new
    # free-tier keys). Override with GEMINI_MODEL if Google's free-tier lineup
    # changes again, e.g. GEMINI_MODEL=gemini-2.5-flash-lite.
    model_name = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")
    return LLM(
        model=f"gemini/{model_name}",
        api_key=api_key,
        temperature=0.4,
    )


def build_agents(llm: LLM):
    """Define the four specialists.

    An Agent in CrewAI is essentially a *persona plus a job description*. The
    role/goal/backstory fields are not decoration - they are injected into the
    system prompt and genuinely change how the model behaves. A good backstory
    is the cheapest quality lever you have.
    """

    # --- The Researcher -----------------------------------------------------
    # First specialist in the chain. Its only job is to produce organized,
    # trustworthy raw material. It does NOT write prose for the reader.
    researcher = Agent(
        role="Senior Research Analyst",
        goal=(
            "Find and organize the most important, accurate facts about the "
            "given topic so a writer can turn them into an article."
        ),
        backstory=(
            "You are a meticulous analyst who has spent years separating signal "
            "from hype. You produce tight, well-structured briefs: key points, "
            "context, and any caveats. You never pad and you flag uncertainty."
        ),
        llm=llm,
        # allow_delegation=False keeps each agent in its lane. Turning it on lets
        # an agent ask teammates for help, which is powerful but harder to reason
        # about for a first example.
        allow_delegation=False,
        verbose=True,
    )

    # --- The Writer ---------------------------------------------------------
    # Second in the chain. It consumes the researcher's brief (via task context,
    # wired below) and shapes it into something a human enjoys reading.
    writer = Agent(
        role="Technical Writer",
        goal=(
            "Turn the research brief into a clear, engaging, well-structured "
            "article for a smart but non-expert reader."
        ),
        backstory=(
            "You are a writer who makes complex topics feel simple without "
            "dumbing them down. You favor plain language, concrete examples, and "
            "a logical flow from idea to idea. You write only from the facts you "
            "are given - you do not invent details."
        ),
        llm=llm,
        allow_delegation=False,
        verbose=True,
    )

    # --- The Critic ---------------------------------------------------------
    # Third in the chain. This is the agent that makes multi-agent systems worth
    # the extra cost: a *separate* set of eyes that was not invested in writing
    # the draft, so it is far more willing to find fault.
    critic = Agent(
        role="Editorial Critic",
        goal=(
            "Rigorously review the draft for accuracy, clarity, and structure, "
            "then return a polished final version - or send it back with specific "
            "fixes if it is not good enough."
        ),
        backstory=(
            "You are a demanding editor. You check claims against the research "
            "brief, hunt for vague sentences, and refuse to let weak writing "
            "ship. When the draft is close, you fix it yourself; when it is not, "
            "you say exactly what must change and why."
        ),
        llm=llm,
        allow_delegation=False,
        verbose=True,
    )

    # --- The Curriculum Designer -------------------------------------------
    # Fourth agent. Unlike the others it does NOT write prose - it emits a
    # structured data file that the HTML teaching page consumes. This is a common
    # real-world role: an agent whose output is machine-readable so a downstream
    # system (here, a web page) can render it. Note the emphasis in the backstory
    # on returning ONLY valid JSON; structured-output agents live or die by how
    # strictly they obey the format contract.
    curriculum_designer = Agent(
        role="Curriculum Designer",
        goal=(
            "Convert the team's understanding of multi-agent systems into a "
            "structured JSON lesson that a web page can render: agent roles, a "
            "glossary, and a step-by-step simulated run."
        ),
        backstory=(
            "You are an instructional designer who turns expert material into "
            "clear lessons for non-technical people. You think in structured "
            "data, not paragraphs. When asked for JSON you return ONLY valid "
            "JSON - no commentary, no markdown code fences, nothing else."
        ),
        llm=llm,
        allow_delegation=False,
        verbose=True,
    )

    return researcher, writer, critic, curriculum_designer


def build_tasks(topic, researcher, writer, critic, curriculum_designer):
    """Define the work and, crucially, how the work HANDS OFF.

    The single most important idea here is `context=[...]`. It is the wiring that
    turns separate agents into a pipeline: the output of one task is fed in as
    background for the next. This is the "handoff" - the same baton-passing that
    handoff_demo.py does manually with f-strings.
    """

    # STEP 1: research. No context, because this is the start of the chain.
    research_task = Task(
        description=(
            f"Research the topic: '{topic}'.\n"
            "Produce a structured brief with 5-8 key points. For each point give "
            "one or two sentences of explanation. Note any important caveats or "
            "areas of disagreement. Keep it factual and organized, not prose."
        ),
        expected_output=(
            "A bulleted research brief of 5-8 key points with short explanations "
            "and any caveats."
        ),
        agent=researcher,
    )

    # STEP 2: write. THE HANDOFF: context=[research_task] means the writer
    # receives the researcher's brief automatically. The writer never has to ask
    # for it - the orchestrator delivers it.
    writing_task = Task(
        description=(
            "Using ONLY the research brief provided to you, write a clear, "
            "engaging article of about 400-500 words for a smart non-expert. "
            "Give it a title, a short intro, a few body sections, and a brief "
            "conclusion. Do not invent facts that are not in the brief."
        ),
        expected_output="A well-structured ~400-500 word article in Markdown.",
        agent=writer,
        context=[research_task],  # <-- handoff: researcher -> writer
    )

    # STEP 3: critique + finalize. THE SECOND HANDOFF plus the FEEDBACK LOOP.
    # The critic sees BOTH the original brief and the draft (context has two
    # items), so it can fact-check the draft against the source material - the
    # core defense against a "hallucination cascade" where one agent's mistake
    # gets amplified downstream.
    #
    # ABOUT THE "SEND IT BACK" LOOP:
    # In this sequential crew the loop is logical, not a literal re-run: we
    # instruct the critic to internally decide "is this good enough?" and, if
    # not, to revise it itself before returning the final version. To make the
    # loop *automatic* (writer actually re-runs on rejection) you would switch
    # the crew to `Process.hierarchical` with a manager agent, or build an
    # explicit loop in code as handoff_demo.py shows. We keep it sequential here
    # because it is the clearest possible first example.
    critique_task = Task(
        description=(
            "Review the draft article against the original research brief.\n"
            "1. Check every claim in the draft against the brief. Flag anything "
            "unsupported.\n"
            "2. Judge clarity, structure, and flow.\n"
            "3. Decide: is this good enough to publish?\n"
            "   - If NO: explain the specific problems, then rewrite the article "
            "to fix them yourself (this is the 'send it back and improve' loop).\n"
            "   - If YES: lightly polish it.\n"
            "Return only the final, publication-ready article."
        ),
        expected_output="The final, polished, publication-ready article in Markdown.",
        agent=critic,
        context=[research_task, writing_task],  # <-- sees brief AND draft
    )

    # STEP 4: design the teaching content as JSON. THE THIRD HANDOFF: this task
    # gets the research brief AND the final article as context, so the lesson it
    # designs is grounded in the crew's own work. Its output is the data that
    # index.html renders.
    curriculum_task = build_curriculum_task(
        curriculum_designer, topic, context=[research_task, critique_task]
    )

    return research_task, writing_task, critique_task, curriculum_task


def build_curriculum_task(curriculum_designer, topic, context):
    """Define the structured-output task.

    The prompt is unusually strict on FORMAT because the consumer is a program,
    not a person. We spell out the exact JSON shape and the exact glossary
    terms. The simulation is scripted around the REAL topic passed on the
    command line (not a fixed example), so the page's walkthrough matches
    whatever you actually researched. The schema here MUST match what
    index.html reads in its render functions, and the FALLBACK_CONTENT dict
    below, which is the safety net if the model ever returns something
    unparseable.
    """
    return Task(
        description=(
            "Design the content for an interactive web page that teaches non-"
            "technical coworkers how a multi-agent system works (an orchestrator "
            "delegating to researcher, writer, and critic agents, where the "
            "critic can send work back).\n\n"
            "Return ONLY a single valid JSON object - no markdown, no code "
            "fences, no text before or after. The object MUST have exactly these "
            "three top-level keys:\n\n"
            "1. \"agents\": an array of EXACTLY 4 objects, in this order, with "
            "these keys:\n"
            "   - \"key\": one of \"orchestrator\", \"researcher\", \"writer\", "
            "\"critic\" (in that order)\n"
            "   - \"tag\": a short label (\"Manager\", \"Step 1\", \"Step 2\", "
            "\"Step 3\")\n"
            "   - \"name\": the display name (\"Orchestrator\", \"Researcher\", "
            "\"Writer\", \"Critic\")\n"
            "   - \"role\": one short sentence naming the role\n"
            "   - \"goal\": one short sentence on what it tries to achieve\n"
            "   - \"plain\": 2-3 sentences of plain-language explanation for a "
            "non-technical reader\n\n"
            "2. \"glossary\": an array of objects, one for EACH of these terms in "
            "this order: Orchestrator, Agent, Tool, MCP (Model Context "
            "Protocol), A2A (Agent-to-Agent), Handoff. Each object has \"term\" "
            "and \"definition\" (one or two plain-language sentences).\n\n"
            f"3. \"simulation\": an array that scripts a step-by-step run of the "
            f"crew on the request 'Research {topic} and write a short summary for "
            f"our team.' Base it on the actual research and article the crew just "
            f"produced (see context) - use real findings about {topic}, not a "
            f"generic placeholder. Each element has:\n"
            "   - \"role\": one of \"orchestrator\", \"researcher\", \"writer\", "
            "\"critic\", \"final\"\n"
            "   - \"label\": display name for that turn\n"
            "   - \"step\": a short progress label (e.g. \"Step 1 of 3\", "
            "\"Looping back\", \"Delivered\")\n"
            "   - \"body\": what that agent says/produces on this turn (plain "
            "text; you may use \\n for line breaks)\n"
            "   - optionally \"reject\": true on the critic turn where it sends "
            "the draft back\n"
            "   - optionally \"approve\": true on the critic turn where it "
            "approves\n"
            "   - optionally \"final\": true on the last element (the delivered "
            "answer)\n"
            "   The simulation MUST include, in order: an orchestrator planning "
            "step, a researcher step, a writer step, a critic step that REJECTS "
            "with reject=true and explains why, an orchestrator 'looping back' "
            "step, a second researcher step, a second writer step, a critic step "
            "that APPROVES with approve=true, and a final element with "
            "final=true containing the polished answer.\n\n"
            f"Keep all writing in sentence case, plain language, no emoji. Make "
            f"the {topic} content concrete and genuinely useful, grounded in "
            f"what the researcher and writer actually produced."
        ),
        expected_output=(
            "A single valid JSON object with keys agents, glossary, and "
            "simulation, and nothing else."
        ),
        agent=curriculum_designer,
        context=context,  # <-- grounded in the research brief + final article
    )


# ---------------------------------------------------------------------------
# Parsing the curriculum agent's output into content.json
# ---------------------------------------------------------------------------

def extract_json(text):
    """Pull a JSON object out of the model's raw text.

    Even when told 'JSON only', models sometimes wrap output in ```json fences or
    add a stray sentence. This is defensive plumbing: strip common code fences,
    then fall back to grabbing the outermost {...} span. Raises ValueError if no
    valid JSON object can be recovered, which the caller turns into a fallback.
    """
    if not text:
        raise ValueError("empty model output")

    cleaned = text.strip()

    # Remove a leading/trailing markdown code fence if present.
    fence = re.match(r"^```(?:json)?\s*(.*?)\s*```$", cleaned, re.DOTALL)
    if fence:
        cleaned = fence.group(1).strip()

    # First try: parse the whole thing.
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        pass

    # Second try: grab the outermost brace span and parse that.
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start != -1 and end != -1 and end > start:
        return json.loads(cleaned[start : end + 1])

    raise ValueError("no JSON object found in model output")


def validate_content(data):
    """Light structural check so we never write garbage to content.json.

    We only assert the shape index.html depends on. If anything essential is
    missing we raise, and the caller writes the known-good FALLBACK_CONTENT
    instead. Better a correct hand-written lesson than a half-broken page.
    """
    if not isinstance(data, dict):
        raise ValueError("top level is not an object")
    for key in ("agents", "glossary", "simulation"):
        if key not in data or not isinstance(data[key], list) or not data[key]:
            raise ValueError(f"missing or empty '{key}'")
    if len(data["agents"]) != 4:
        raise ValueError("expected exactly 4 agents")
    for a in data["agents"]:
        for field in ("key", "tag", "name", "role", "goal", "plain"):
            if not a.get(field):
                raise ValueError(f"agent missing '{field}'")
    for g in data["glossary"]:
        if not g.get("term") or not g.get("definition"):
            raise ValueError("glossary entry missing term/definition")
    for s in data["simulation"]:
        for field in ("role", "label", "step", "body"):
            if not s.get(field):
                raise ValueError(f"simulation step missing '{field}'")
    return data


def write_content(data, source):
    """Write the validated content to content.json and report where it came from."""
    payload = dict(data)
    payload["_meta"] = {"source": source}  # so the page/dev can see the origin
    with open(CONTENT_PATH, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
    print(f"\n[content] wrote {CONTENT_PATH} (source: {source})")


# The safety net. This is hand-written, known-good content that matches the exact
# schema the curriculum agent is asked to produce. If the model's JSON cannot be
# parsed or validated, we write this instead so index.html always has good data.
FALLBACK_CONTENT = {
    "request": "Research SaaS pricing models and write a short summary for our team.",
    "agents": [
        {
            "key": "orchestrator", "tag": "Manager", "name": "Orchestrator",
            "role": "Runs the whole job and decides the order of work.",
            "goal": "Break the request into steps and pass each result to the next agent.",
            "plain": "The team lead. It does not do the research or writing itself. It decides who works when, hands each agent what it needs, and decides when the work is finished. In the Python demo this is CrewAI's crew, not a separate prompt.",
        },
        {
            "key": "researcher", "tag": "Step 1", "name": "Researcher",
            "role": "Senior research analyst.",
            "goal": "Gather and organize the most important, accurate facts.",
            "plain": "Goes first. It collects raw facts and lays them out as a tidy brief of key points and caveats. It does not write the final piece, it just makes sure the facts are right and well organized.",
        },
        {
            "key": "writer", "tag": "Step 2", "name": "Writer",
            "role": "Technical writer.",
            "goal": "Turn the research brief into a clear, readable article.",
            "plain": "Takes the researcher's brief and shapes it into something pleasant to read. It only uses the facts it was handed, so it cannot wander off and invent things.",
        },
        {
            "key": "critic", "tag": "Step 3", "name": "Critic",
            "role": "Editorial critic.",
            "goal": "Check the draft against the facts and approve it or send it back.",
            "plain": "The fresh set of eyes. It compares the draft with the original research, catches mistakes and fuzzy writing, and either polishes it or rejects it with specific fixes. This feedback loop is what makes the team better than any single agent.",
        },
    ],
    "glossary": [
        {"term": "Orchestrator", "definition": "The manager agent. It breaks a request into steps, decides which agent does each step, passes results along, and decides when the job is done."},
        {"term": "Agent", "definition": "A single AI worker with a defined role, goal, and personality. On its own it is one language model; the power comes from combining several."},
        {"term": "Tool", "definition": "Something an agent can use beyond just talking, such as a web search, a database, or a calculator. Tools let agents act on the real world, not only describe it."},
        {"term": "MCP (Model Context Protocol)", "definition": "An open standard for the tool layer: a common way for any agent to discover and use external tools and data. Build the connector once, and any MCP-aware agent can use it."},
        {"term": "A2A (Agent-to-Agent)", "definition": "An open standard for the agent layer: a common way for separate agents, even from different teams or frameworks, to find each other and delegate tasks."},
        {"term": "Handoff", "definition": "The moment one agent passes its output to the next agent as input. It is the heart of a multi-agent system, and it is literally just one result becoming the next prompt."},
    ],
    "simulation": [
        {"role": "orchestrator", "label": "Orchestrator", "step": "Planning", "body": "Request received. Plan: 1) research SaaS pricing models, 2) write a short summary, 3) review before sending. Handing off to the researcher."},
        {"role": "researcher", "label": "Researcher", "step": "Step 1 of 3", "body": "Brief:\n- Flat-rate: one price for everything. Simple, but does not scale with value.\n- Per-seat: priced per user. Predictable, common in B2B.\n- Usage-based: pay for what you use. Aligns cost with value, harder to forecast.\n- Tiered: good / better / best bundles. Nudges upgrades.\n- Freemium: free entry tier to drive adoption, paid upgrades."},
        {"role": "writer", "label": "Writer", "step": "Step 2 of 3", "body": "Draft: \"SaaS companies price in a few main ways. Some charge a flat fee, others charge per user, and many now charge based on usage. Tiered plans and freemium offers are also popular. Pick the one that fits your customers.\""},
        {"role": "critic", "label": "Critic", "step": "Step 3 of 3", "reject": True, "body": "REVISE. The draft lists the models but never explains the trade-off that the team actually asked about. It is too vague to act on. Sending it back: add the key trade-off for each model and a one-line recommendation."},
        {"role": "orchestrator", "label": "Orchestrator", "step": "Looping back", "body": "Critic rejected the draft. Re-running research and writing with the critic's notes. (Retries are capped so this cannot loop forever.)"},
        {"role": "researcher", "label": "Researcher", "step": "Step 1, round 2", "body": "Refined brief with trade-offs:\n- Per-seat: predictable revenue, but penalizes teams for adding users.\n- Usage-based: revenue grows with value delivered, but bills are harder to predict.\n- Tiered + freemium together: free tier fills the funnel; tiers move buyers up.\nRecommendation hint: most modern B2B SaaS blends per-seat with usage-based."},
        {"role": "writer", "label": "Writer", "step": "Step 2, round 2", "body": "Revised draft: \"There are five common SaaS pricing models, each with a trade-off. Per-seat pricing is predictable but discourages adding users. Usage-based pricing grows with the value customers get, though bills are harder to forecast. Tiered plans and a freemium tier work well together to attract users and move them upmarket. For most B2B products today, a blend of per-seat and usage-based pricing is the safest starting point.\""},
        {"role": "critic", "label": "Critic", "step": "Step 3, round 2", "approve": True, "body": "APPROVED. Every model now has its trade-off, and there is a clear recommendation the team can act on. Accuracy checks out against the brief. Polishing lightly and finalizing."},
        {"role": "final", "label": "Final answer", "step": "Delivered", "final": True, "body": "There are five common SaaS pricing models, each with a trade-off. Per-seat pricing is predictable but discourages adding users. Usage-based pricing grows with the value customers receive, though bills are harder to forecast. Tiered plans and a freemium tier pair well: the free tier fills the funnel and the tiers move buyers upmarket. For most B2B products today, a blend of per-seat and usage-based pricing is the safest starting point."},
    ],
}


def save_curriculum(curriculum_output, topic):
    """Parse the curriculum agent's raw output and persist content.json.

    This is the try/except + sane fallback the lesson is built around: we attempt
    to extract and validate the model's JSON; if anything goes wrong we log it and
    write the known-good FALLBACK_CONTENT so the teaching page never breaks.
    """
    # The "incoming request" banner index.html shows above the simulation is
    # built from the real topic here, in Python, rather than asked of the
    # model - it is plain string formatting, so it is always correct and
    # always matches what was actually run, even if the LLM's JSON is wonky.
    request_line = f"Research {topic} and write a short summary for our team."
    raw = getattr(curriculum_output, "raw", None) or str(curriculum_output)
    try:
        data = validate_content(extract_json(raw))
        data["request"] = request_line
        write_content(data, source="crew")
    except (ValueError, json.JSONDecodeError) as err:
        print(f"\n[content] could not parse crew JSON ({err}); using fallback content.")
        fallback = dict(FALLBACK_CONTENT)
        fallback["request"] = request_line
        write_content(fallback, source="fallback")


def main() -> None:
    # The topic comes from the command line; everything after the script name is
    # joined so quoting is optional. Falls back to a sensible default.
    topic = " ".join(sys.argv[1:]).strip() or "multi-agent AI systems"

    print(f"\n=== Multi-agent crew starting on topic: {topic!r} ===\n")

    llm = build_llm()
    researcher, writer, critic, curriculum_designer = build_agents(llm)
    research_task, writing_task, critique_task, curriculum_task = build_tasks(
        topic, researcher, writer, critic, curriculum_designer
    )

    # The Crew is the ORCHESTRATOR. `Process.sequential` means: run the tasks in
    # order, and (because we wired context=[...]) feed each result forward. The
    # crew is what turns a pile of agents and tasks into a working assembly line.
    crew = Crew(
        agents=[researcher, writer, critic, curriculum_designer],
        tasks=[research_task, writing_task, critique_task, curriculum_task],
        process=Process.sequential,
        verbose=True,
    )

    # kickoff() runs the whole pipeline. The CrewOutput it returns exposes every
    # task's result in .tasks_output, so we can grab BOTH the critic's final
    # article and the curriculum designer's JSON.
    result = crew.kickoff()

    # tasks_output is in the same order as the tasks list above.
    article_output = result.tasks_output[2]      # critic's final article
    curriculum_output = result.tasks_output[3]   # curriculum designer's JSON

    # Persist the teaching content (with parsing fallback) for index.html.
    save_curriculum(curriculum_output, topic)

    print("\n\n========== FINAL ARTICLE ==========\n")
    print(article_output)
    print("\n===================================\n")
    print("Open index.html to see the crew-generated lesson (it reads content.json).")


if __name__ == "__main__":
    main()
